TRANSMOG_CLASS_MASK = {
  [256] = { CLASS_FILE_NAME = "WARLOCK", NAME = "术士" },
  [128] = { CLASS_FILE_NAME = "MAGE", NAME = "法师" },
  [16] = { CLASS_FILE_NAME = "PRIEST", NAME = "牧师" },
  --
  [8] = { CLASS_FILE_NAME = "ROGUE", NAME = "盗贼" },
  [2048] = { CLASS_FILE_NAME = "DEMONHUNTER", NAME = "恶魔猎手" },
  [1024] = { CLASS_FILE_NAME = "DRUID", NAME = "德鲁伊" },
  [512] = { CLASS_FILE_NAME = "MONK", NAME = "武僧" },
  --
  [4] = { CLASS_FILE_NAME = "HUNTER", NAME = "猎人" },
  [64] = { CLASS_FILE_NAME = "SHAMAN", NAME = "萨满" },
  [4096] = { CLASS_FILE_NAME = "EVOKER", NAME = "唤魔师" },
  --
  [1] = { CLASS_FILE_NAME = "WARRIOR", NAME = "战士" },
  [2] = { CLASS_FILE_NAME = "PALADIN", NAME = "圣骑士" },
  [32] = { CLASS_FILE_NAME = "DEATHKNIGHT", NAME = "死亡骑士" },
}

-- 定义遍历顺序
TRANSMOG_CLASS_MASK_ORDER = {
  256, 128, 16,       -- 第一组
  8, 2048, 1024, 512, -- 第二组
  4, 64, 4096,        -- 第三组
  1, 2, 32,           -- 第四组
}

TRANSMOG_SETS = {
  {
    LABEL = "烈毒之渊",
    SETS = {
      { SET_ID = 5837, NAME = "灾厄墓骑的熔炉", DESCRIPTION = "随机团队", CLASS_MASK = 32 },
      { SET_ID = 5838, NAME = "灾厄墓骑的熔炉", DESCRIPTION = "普通", CLASS_MASK = 32 },
      { SET_ID = 5839, NAME = "灾厄墓骑的熔炉", DESCRIPTION = "英雄", CLASS_MASK = 32 },
      { SET_ID = 5840, NAME = "灾厄墓骑的熔炉", DESCRIPTION = "史诗", CLASS_MASK = 32 },
      { SET_ID = 5841, NAME = "深渊末日猎犬的追击", DESCRIPTION = "随机团队", CLASS_MASK = 2048 },
      { SET_ID = 5842, NAME = "深渊末日猎犬的追击", DESCRIPTION = "普通", CLASS_MASK = 2048 },
      { SET_ID = 5843, NAME = "深渊末日猎犬的追击", DESCRIPTION = "英雄", CLASS_MASK = 2048 },
      { SET_ID = 5844, NAME = "深渊末日猎犬的追击", DESCRIPTION = "史诗", CLASS_MASK = 2048 },
      { SET_ID = 5845, NAME = "神秘梦境守望者的树皮", DESCRIPTION = "随机团队", CLASS_MASK = 1024 },
      { SET_ID = 5846, NAME = "神秘梦境守望者的树皮", DESCRIPTION = "普通", CLASS_MASK = 1024 },
      { SET_ID = 5847, NAME = "神秘梦境守望者的树皮", DESCRIPTION = "英雄", CLASS_MASK = 1024 },
      { SET_ID = 5848, NAME = "神秘梦境守望者的树皮", DESCRIPTION = "史诗", CLASS_MASK = 1024 },
      { SET_ID = 5849, NAME = "灾厄回响", DESCRIPTION = "随机团队", CLASS_MASK = 4096 },
      { SET_ID = 5850, NAME = "灾厄回响", DESCRIPTION = "普通", CLASS_MASK = 4096 },
      { SET_ID = 5851, NAME = "灾厄回响", DESCRIPTION = "英雄", CLASS_MASK = 4096 },
      { SET_ID = 5852, NAME = "灾厄回响", DESCRIPTION = "史诗", CLASS_MASK = 4096 },
      { SET_ID = 5853, NAME = "潜伏蝰蛇的伏击", DESCRIPTION = "随机团队", CLASS_MASK = 4 },
      { SET_ID = 5854, NAME = "潜伏蝰蛇的伏击", DESCRIPTION = "普通", CLASS_MASK = 4 },
      { SET_ID = 5855, NAME = "潜伏蝰蛇的伏击", DESCRIPTION = "英雄", CLASS_MASK = 4 },
      { SET_ID = 5856, NAME = "潜伏蝰蛇的伏击", DESCRIPTION = "史诗", CLASS_MASK = 4 },
      { SET_ID = 5857, NAME = "始源魔网守卫的装束", DESCRIPTION = "随机团队", CLASS_MASK = 128 },
      { SET_ID = 5858, NAME = "始源魔网守卫的装束", DESCRIPTION = "普通", CLASS_MASK = 128 },
      { SET_ID = 5859, NAME = "始源魔网守卫的装束", DESCRIPTION = "英雄", CLASS_MASK = 128 },
      { SET_ID = 5860, NAME = "始源魔网守卫的装束", DESCRIPTION = "史诗", CLASS_MASK = 128 },
      { SET_ID = 5861, NAME = "美猴王的诡计", DESCRIPTION = "随机团队", CLASS_MASK = 512 },
      { SET_ID = 5862, NAME = "美猴王的诡计", DESCRIPTION = "普通", CLASS_MASK = 512 },
      { SET_ID = 5863, NAME = "美猴王的诡计", DESCRIPTION = "英雄", CLASS_MASK = 512 },
      { SET_ID = 5864, NAME = "美猴王的诡计", DESCRIPTION = "史诗", CLASS_MASK = 512 },
      { SET_ID = 5865, NAME = "祝圣烈焰之耀", DESCRIPTION = "随机团队", CLASS_MASK = 2 },
      { SET_ID = 5866, NAME = "祝圣烈焰之耀", DESCRIPTION = "普通", CLASS_MASK = 2 },
      { SET_ID = 5867, NAME = "祝圣烈焰之耀", DESCRIPTION = "英雄", CLASS_MASK = 2 },
      { SET_ID = 5868, NAME = "祝圣烈焰之耀", DESCRIPTION = "史诗", CLASS_MASK = 2 },
      { SET_ID = 5869, NAME = "宇宙忏悔者的法服", DESCRIPTION = "随机团队", CLASS_MASK = 16 },
      { SET_ID = 5870, NAME = "宇宙忏悔者的法服", DESCRIPTION = "普通", CLASS_MASK = 16 },
      { SET_ID = 5871, NAME = "宇宙忏悔者的法服", DESCRIPTION = "英雄", CLASS_MASK = 16 },
      { SET_ID = 5872, NAME = "宇宙忏悔者的法服", DESCRIPTION = "史诗", CLASS_MASK = 16 },
      { SET_ID = 5873, NAME = "天选屠血者的妖纹", DESCRIPTION = "随机团队", CLASS_MASK = 8 },
      { SET_ID = 5874, NAME = "天选屠血者的妖纹", DESCRIPTION = "普通", CLASS_MASK = 8 },
      { SET_ID = 5875, NAME = "天选屠血者的妖纹", DESCRIPTION = "英雄", CLASS_MASK = 8 },
      { SET_ID = 5876, NAME = "天选屠血者的妖纹", DESCRIPTION = "史诗", CLASS_MASK = 8 },
      { SET_ID = 5877, NAME = "蛇裔神谕者的预言", DESCRIPTION = "随机团队", CLASS_MASK = 64 },
      { SET_ID = 5878, NAME = "蛇裔神谕者的预言", DESCRIPTION = "普通", CLASS_MASK = 64 },
      { SET_ID = 5879, NAME = "蛇裔神谕者的预言", DESCRIPTION = "英雄", CLASS_MASK = 64 },
      { SET_ID = 5880, NAME = "蛇裔神谕者的预言", DESCRIPTION = "史诗", CLASS_MASK = 64 },
      { SET_ID = 5881, NAME = "受诅通灵师碎裂束缚", DESCRIPTION = "随机团队", CLASS_MASK = 256 },
      { SET_ID = 5882, NAME = "受诅通灵师碎裂束缚", DESCRIPTION = "普通", CLASS_MASK = 256 },
      { SET_ID = 5883, NAME = "受诅通灵师碎裂束缚", DESCRIPTION = "英雄", CLASS_MASK = 256 },
      { SET_ID = 5884, NAME = "受诅通灵师碎裂束缚", DESCRIPTION = "史诗", CLASS_MASK = 256 },
      { SET_ID = 5885, NAME = "翡翠督军的统御", DESCRIPTION = "随机团队", CLASS_MASK = 1 },
      { SET_ID = 5886, NAME = "翡翠督军的统御", DESCRIPTION = "普通", CLASS_MASK = 1 },
      { SET_ID = 5887, NAME = "翡翠督军的统御", DESCRIPTION = "英雄", CLASS_MASK = 1 },
      { SET_ID = 5888, NAME = "翡翠督军的统御", DESCRIPTION = "史诗", CLASS_MASK = 1 } }
  },
  {
    LABEL = "阿梅达希尔，梦境之愿",
    SETS = {
      { SET_ID = 3138, NAME = "燃焰猎梦者的战利品", DESCRIPTION = "随机团队", CLASS_MASK = 4 },
      { SET_ID = 3137, NAME = "燃焰猎梦者的战利品", DESCRIPTION = "普通", CLASS_MASK = 4 },
      { SET_ID = 3140, NAME = "燃焰猎梦者的战利品", DESCRIPTION = "英雄", CLASS_MASK = 4 },
      { SET_ID = 3139, NAME = "燃焰猎梦者的战利品", DESCRIPTION = "史诗", CLASS_MASK = 4 },
      { SET_ID = 3142, NAME = "幽鹭之诫", DESCRIPTION = "随机团队", CLASS_MASK = 512 },
      { SET_ID = 3144, NAME = "幽鹭之诫", DESCRIPTION = "普通", CLASS_MASK = 512 },
      { SET_ID = 3143, NAME = "幽鹭之诫", DESCRIPTION = "英雄", CLASS_MASK = 512 },
      { SET_ID = 3141, NAME = "幽鹭之诫", DESCRIPTION = "史诗", CLASS_MASK = 512 },
      { SET_ID = 3147, NAME = "狂热薪火骑士的炽情", DESCRIPTION = "随机团队", CLASS_MASK = 2 },
      { SET_ID = 3148, NAME = "狂热薪火骑士的炽情", DESCRIPTION = "普通", CLASS_MASK = 2 },
      { SET_ID = 3146, NAME = "狂热薪火骑士的炽情", DESCRIPTION = "英雄", CLASS_MASK = 2 },
      { SET_ID = 3145, NAME = "狂热薪火骑士的炽情", DESCRIPTION = "史诗", CLASS_MASK = 2 },
      { SET_ID = 3152, NAME = "熔火先锋的迫击板甲", DESCRIPTION = "随机团队", CLASS_MASK = 1 },
      { SET_ID = 3150, NAME = "熔火先锋的迫击板甲", DESCRIPTION = "普通", CLASS_MASK = 1 },
      { SET_ID = 3149, NAME = "熔火先锋的迫击板甲", DESCRIPTION = "英雄", CLASS_MASK = 1 },
      { SET_ID = 3151, NAME = "熔火先锋的迫击板甲", DESCRIPTION = "史诗", CLASS_MASK = 1 },
      { SET_ID = 3154, NAME = "尖嚎炬魔的暴行", DESCRIPTION = "随机团队", CLASS_MASK = 2048 },
      { SET_ID = 3153, NAME = "尖嚎炬魔的暴行", DESCRIPTION = "普通", CLASS_MASK = 2048 },
      { SET_ID = 3155, NAME = "尖嚎炬魔的暴行", DESCRIPTION = "英雄", CLASS_MASK = 2048 },
      { SET_ID = 3156, NAME = "尖嚎炬魔的暴行", DESCRIPTION = "史诗", CLASS_MASK = 2048 },
      { SET_ID = 3160, NAME = "军营守护者的永恒警戒", DESCRIPTION = "随机团队", CLASS_MASK = 4096 },
      { SET_ID = 3157, NAME = "军营守护者的永恒警戒", DESCRIPTION = "普通", CLASS_MASK = 4096 },
      { SET_ID = 3158, NAME = "军营守护者的永恒警戒", DESCRIPTION = "英雄", CLASS_MASK = 4096 },
      { SET_ID = 3159, NAME = "军营守护者的永恒警戒", DESCRIPTION = "史诗", CLASS_MASK = 4096 },
      { SET_ID = 3162, NAME = "复生梦魇的沉墓衣钵", DESCRIPTION = "随机团队", CLASS_MASK = 32 },
      { SET_ID = 3163, NAME = "复生梦魇的沉墓衣钵", DESCRIPTION = "普通", CLASS_MASK = 32 },
      { SET_ID = 3161, NAME = "复生梦魇的沉墓衣钵", DESCRIPTION = "英雄", CLASS_MASK = 32 },
      { SET_ID = 3164, NAME = "复生梦魇的沉墓衣钵", DESCRIPTION = "史诗", CLASS_MASK = 32 },
      { SET_ID = 3167, NAME = "清醒阴翳行者的沉默", DESCRIPTION = "随机团队", CLASS_MASK = 8 },
      { SET_ID = 3165, NAME = "清醒阴翳行者的沉默", DESCRIPTION = "普通", CLASS_MASK = 8 },
      { SET_ID = 3168, NAME = "清醒阴翳行者的沉默", DESCRIPTION = "英雄", CLASS_MASK = 8 },
      { SET_ID = 3166, NAME = "清醒阴翳行者的沉默", DESCRIPTION = "史诗", CLASS_MASK = 8 },
      { SET_ID = 3171, NAME = "巨狼流放者的幻视", DESCRIPTION = "随机团队", CLASS_MASK = 64 },
      { SET_ID = 3169, NAME = "巨狼流放者的幻视", DESCRIPTION = "普通", CLASS_MASK = 64 },
      { SET_ID = 3170, NAME = "巨狼流放者的幻视", DESCRIPTION = "英雄", CLASS_MASK = 64 },
      { SET_ID = 3172, NAME = "巨狼流放者的幻视", DESCRIPTION = "史诗", CLASS_MASK = 64 },
      { SET_ID = 3176, NAME = "虔诚烬魔的契纹", DESCRIPTION = "随机团队", CLASS_MASK = 256 },
      { SET_ID = 3175, NAME = "虔诚烬魔的契纹", DESCRIPTION = "普通", CLASS_MASK = 256 },
      { SET_ID = 3174, NAME = "虔诚烬魔的契纹", DESCRIPTION = "英雄", CLASS_MASK = 256 },
      { SET_ID = 3173, NAME = "虔诚烬魔的契纹", DESCRIPTION = "史诗", CLASS_MASK = 256 },
      { SET_ID = 3179, NAME = "仁爱灰烬贤者的启迪", DESCRIPTION = "随机团队", CLASS_MASK = 1024 },
      { SET_ID = 3177, NAME = "仁爱灰烬贤者的启迪", DESCRIPTION = "普通", CLASS_MASK = 1024 },
      { SET_ID = 3178, NAME = "仁爱灰烬贤者的启迪", DESCRIPTION = "英雄", CLASS_MASK = 1024 },
      { SET_ID = 3180, NAME = "仁爱灰烬贤者的启迪", DESCRIPTION = "史诗", CLASS_MASK = 1024 },
      { SET_ID = 3181, NAME = "月光教派的祝福", DESCRIPTION = "随机团队", CLASS_MASK = 16 },
      { SET_ID = 3184, NAME = "月光教派的祝福", DESCRIPTION = "普通", CLASS_MASK = 16 },
      { SET_ID = 3183, NAME = "月光教派的祝福", DESCRIPTION = "英雄", CLASS_MASK = 16 },
      { SET_ID = 3182, NAME = "月光教派的祝福", DESCRIPTION = "史诗", CLASS_MASK = 16 },
      { SET_ID = 3185, NAME = "忤逆时光术师的发条", DESCRIPTION = "随机团队", CLASS_MASK = 128 },
      { SET_ID = 3186, NAME = "忤逆时光术师的发条", DESCRIPTION = "普通", CLASS_MASK = 128 },
      { SET_ID = 3187, NAME = "忤逆时光术师的发条", DESCRIPTION = "英雄", CLASS_MASK = 128 },
      { SET_ID = 3188, NAME = "忤逆时光术师的发条", DESCRIPTION = "史诗", CLASS_MASK = 128 },
    }
  },
  {
    LABEL = "亚贝鲁斯，焰影熔炉",
    SETS = {
      { SET_ID = 2900, NAME = "缟玛瑙熔炉铁卫", DESCRIPTION = "随机团队", CLASS_MASK = 1 },
      { SET_ID = 2858, NAME = "缟玛瑙熔炉铁卫", DESCRIPTION = "普通", CLASS_MASK = 1 },
      { SET_ID = 2898, NAME = "缟玛瑙熔炉铁卫", DESCRIPTION = "英雄", CLASS_MASK = 1 },
      { SET_ID = 2899, NAME = "缟玛瑙熔炉铁卫", DESCRIPTION = "史诗", CLASS_MASK = 1 },
      { SET_ID = 2873, NAME = "心火哨兵的权威", DESCRIPTION = "随机团队", CLASS_MASK = 2 },
      { SET_ID = 2859, NAME = "心火哨兵的权威", DESCRIPTION = "普通", CLASS_MASK = 2 },
      { SET_ID = 2871, NAME = "心火哨兵的权威", DESCRIPTION = "英雄", CLASS_MASK = 2 },
      { SET_ID = 2872, NAME = "心火哨兵的权威", DESCRIPTION = "史诗", CLASS_MASK = 2 },
      { SET_ID = 2891, NAME = "灰烬掠食者的鳞躯", DESCRIPTION = "随机团队", CLASS_MASK = 4 },
      { SET_ID = 2866, NAME = "灰烬掠食者的鳞躯", DESCRIPTION = "普通", CLASS_MASK = 4 },
      { SET_ID = 2889, NAME = "灰烬掠食者的鳞躯", DESCRIPTION = "英雄", CLASS_MASK = 4 },
      { SET_ID = 2890, NAME = "灰烬掠食者的鳞躯", DESCRIPTION = "史诗", CLASS_MASK = 4 },
      { SET_ID = 2882, NAME = "隐秘魔灵的影纹战甲", DESCRIPTION = "随机团队", CLASS_MASK = 8 },
      { SET_ID = 2862, NAME = "隐秘魔灵的影纹战甲", DESCRIPTION = "普通", CLASS_MASK = 8 },
      { SET_ID = 2880, NAME = "隐秘魔灵的影纹战甲", DESCRIPTION = "英雄", CLASS_MASK = 8 },
      { SET_ID = 2881, NAME = "隐秘魔灵的影纹战甲", DESCRIPTION = "史诗", CLASS_MASK = 8 },
      { SET_ID = 2885, NAME = "炉翼炽天使之裁", DESCRIPTION = "随机团队", CLASS_MASK = 16 },
      { SET_ID = 2863, NAME = "炉翼炽天使之裁", DESCRIPTION = "普通", CLASS_MASK = 16 },
      { SET_ID = 2883, NAME = "炉翼炽天使之裁", DESCRIPTION = "英雄", CLASS_MASK = 16 },
      { SET_ID = 2884, NAME = "炉翼炽天使之裁", DESCRIPTION = "史诗", CLASS_MASK = 16 },
      { SET_ID = 2897, NAME = "徘徊幻影禁咒", DESCRIPTION = "随机团队", CLASS_MASK = 32 },
      { SET_ID = 2870, NAME = "徘徊幻影禁咒", DESCRIPTION = "普通", CLASS_MASK = 32 },
      { SET_ID = 2895, NAME = "徘徊幻影禁咒", DESCRIPTION = "英雄", CLASS_MASK = 32 },
      { SET_ID = 2896, NAME = "徘徊幻影禁咒", DESCRIPTION = "史诗", CLASS_MASK = 32 },
      { SET_ID = 2879, NAME = "焰烬之狼的符文", DESCRIPTION = "随机团队", CLASS_MASK = 64 },
      { SET_ID = 2861, NAME = "焰烬之狼的符文", DESCRIPTION = "普通", CLASS_MASK = 64 },
      { SET_ID = 2877, NAME = "焰烬之狼的符文", DESCRIPTION = "英雄", CLASS_MASK = 64 },
      { SET_ID = 2878, NAME = "焰烬之狼的符文", DESCRIPTION = "史诗", CLASS_MASK = 64 },
      { SET_ID = 2909, NAME = "幽光咒法师之慧", DESCRIPTION = "随机团队", CLASS_MASK = 128 },
      { SET_ID = 2865, NAME = "幽光咒法师之慧", DESCRIPTION = "普通", CLASS_MASK = 128 },
      { SET_ID = 2907, NAME = "幽光咒法师之慧", DESCRIPTION = "英雄", CLASS_MASK = 128 },
      { SET_ID = 2908, NAME = "幽光咒法师之慧", DESCRIPTION = "史诗", CLASS_MASK = 128 },
      { SET_ID = 2876, NAME = "险恶学者的咒衣", DESCRIPTION = "随机团队", CLASS_MASK = 256 },
      { SET_ID = 2860, NAME = "险恶学者的咒衣", DESCRIPTION = "普通", CLASS_MASK = 256 },
      { SET_ID = 2874, NAME = "险恶学者的咒衣", DESCRIPTION = "英雄", CLASS_MASK = 256 },
      { SET_ID = 2875, NAME = "险恶学者的咒衣", DESCRIPTION = "史诗", CLASS_MASK = 256 },
      { SET_ID = 2888, NAME = "朱锻獠牙", DESCRIPTION = "随机团队", CLASS_MASK = 512 },
      { SET_ID = 2864, NAME = "朱锻獠牙", DESCRIPTION = "普通", CLASS_MASK = 512 },
      { SET_ID = 2886, NAME = "朱锻獠牙", DESCRIPTION = "英雄", CLASS_MASK = 512 },
      { SET_ID = 2887, NAME = "朱锻獠牙", DESCRIPTION = "史诗", CLASS_MASK = 512 },
      { SET_ID = 2894, NAME = "秋阳余晖光缕", DESCRIPTION = "随机团队", CLASS_MASK = 1024 },
      { SET_ID = 2868, NAME = "秋阳余晖光缕", DESCRIPTION = "普通", CLASS_MASK = 1024 },
      { SET_ID = 2892, NAME = "秋阳余晖光缕", DESCRIPTION = "英雄", CLASS_MASK = 1024 },
      { SET_ID = 2893, NAME = "秋阳余晖光缕", DESCRIPTION = "史诗", CLASS_MASK = 1024 },
      { SET_ID = 2903, NAME = "弑亲者的负担", DESCRIPTION = "随机团队", CLASS_MASK = 2048 },
      { SET_ID = 2869, NAME = "弑亲者的负担", DESCRIPTION = "普通", CLASS_MASK = 2048 },
      { SET_ID = 2901, NAME = "弑亲者的负担", DESCRIPTION = "英雄", CLASS_MASK = 2048 },
      { SET_ID = 2902, NAME = "弑亲者的负担", DESCRIPTION = "史诗", CLASS_MASK = 2048 },
      { SET_ID = 2906, NAME = "黑曜奥秘的传承", DESCRIPTION = "随机团队", CLASS_MASK = 4096 },
      { SET_ID = 2867, NAME = "黑曜奥秘的传承", DESCRIPTION = "普通", CLASS_MASK = 4096 },
      { SET_ID = 2904, NAME = "黑曜奥秘的传承", DESCRIPTION = "英雄", CLASS_MASK = 4096 },
      { SET_ID = 2905, NAME = "黑曜奥秘的传承", DESCRIPTION = "史诗", CLASS_MASK = 4096 },
    }
  },
  {
    LABEL = "化身巨龙牢窟",
    SETS = {
      { SET_ID = 2652, NAME = "行走高山之岩", DESCRIPTION = "随机团队", CLASS_MASK = 1 },
      { SET_ID = 2613, NAME = "行走高山之岩", DESCRIPTION = "普通", CLASS_MASK = 1 },
      { SET_ID = 2650, NAME = "行走高山之岩", DESCRIPTION = "英雄", CLASS_MASK = 1 },
      { SET_ID = 2651, NAME = "行走高山之岩", DESCRIPTION = "史诗", CLASS_MASK = 1 },
      { SET_ID = 2637, NAME = "美德白银甲胄", DESCRIPTION = "随机团队", CLASS_MASK = 2 },
      { SET_ID = 2608, NAME = "美德白银甲胄", DESCRIPTION = "普通", CLASS_MASK = 2 },
      { SET_ID = 2635, NAME = "美德白银甲胄", DESCRIPTION = "英雄", CLASS_MASK = 2 },
      { SET_ID = 2636, NAME = "美德白银甲胄", DESCRIPTION = "史诗", CLASS_MASK = 2 },
      { SET_ID = 2628, NAME = "雷翼劫猎者的伪装", DESCRIPTION = "随机团队", CLASS_MASK = 4 },
      { SET_ID = 2605, NAME = "雷翼劫猎者的伪装", DESCRIPTION = "普通", CLASS_MASK = 4 },
      { SET_ID = 2626, NAME = "雷翼劫猎者的伪装", DESCRIPTION = "英雄", CLASS_MASK = 4 },
      { SET_ID = 2627, NAME = "雷翼劫猎者的伪装", DESCRIPTION = "史诗", CLASS_MASK = 4 },
      { SET_ID = 2643, NAME = "牢窟探秘者的工具", DESCRIPTION = "随机团队", CLASS_MASK = 8 },
      { SET_ID = 2610, NAME = "牢窟探秘者的工具", DESCRIPTION = "普通", CLASS_MASK = 8 },
      { SET_ID = 2641, NAME = "牢窟探秘者的工具", DESCRIPTION = "英雄", CLASS_MASK = 8 },
      { SET_ID = 2642, NAME = "牢窟探秘者的工具", DESCRIPTION = "史诗", CLASS_MASK = 8 },
      { SET_ID = 2640, NAME = "巨龙圣职者的华服", DESCRIPTION = "随机团队", CLASS_MASK = 16 },
      { SET_ID = 2609, NAME = "巨龙圣职者的华服", DESCRIPTION = "普通", CLASS_MASK = 16 },
      { SET_ID = 2638, NAME = "巨龙圣职者的华服", DESCRIPTION = "英雄", CLASS_MASK = 16 },
      { SET_ID = 2639, NAME = "巨龙圣职者的华服", DESCRIPTION = "史诗", CLASS_MASK = 16 },
      { SET_ID = 2616, NAME = "魅影霜巢遗骸", DESCRIPTION = "随机团队", CLASS_MASK = 32 },
      { SET_ID = 2601, NAME = "魅影霜巢遗骸", DESCRIPTION = "普通", CLASS_MASK = 32 },
      { SET_ID = 2614, NAME = "魅影霜巢遗骸", DESCRIPTION = "英雄", CLASS_MASK = 32 },
      { SET_ID = 2615, NAME = "魅影霜巢遗骸", DESCRIPTION = "史诗", CLASS_MASK = 32 },
      { SET_ID = 2646, NAME = "注能大地元素", DESCRIPTION = "随机团队", CLASS_MASK = 64 },
      { SET_ID = 2611, NAME = "注能大地元素", DESCRIPTION = "普通", CLASS_MASK = 64 },
      { SET_ID = 2644, NAME = "注能大地元素", DESCRIPTION = "英雄", CLASS_MASK = 64 },
      { SET_ID = 2645, NAME = "注能大地元素", DESCRIPTION = "史诗", CLASS_MASK = 64 },
      { SET_ID = 2631, NAME = "水晶学士之缚", DESCRIPTION = "随机团队", CLASS_MASK = 128 },
      { SET_ID = 2606, NAME = "水晶学士之缚", DESCRIPTION = "普通", CLASS_MASK = 128 },
      { SET_ID = 2629, NAME = "水晶学士之缚", DESCRIPTION = "英雄", CLASS_MASK = 128 },
      { SET_ID = 2630, NAME = "水晶学士之缚", DESCRIPTION = "史诗", CLASS_MASK = 128 },
      { SET_ID = 2649, NAME = "鳞誓教徒的向往", DESCRIPTION = "随机团队", CLASS_MASK = 256 },
      { SET_ID = 2612, NAME = "鳞誓教徒的向往", DESCRIPTION = "普通", CLASS_MASK = 256 },
      { SET_ID = 2647, NAME = "鳞誓教徒的向往", DESCRIPTION = "英雄", CLASS_MASK = 256 },
      { SET_ID = 2648, NAME = "鳞誓教徒的向往", DESCRIPTION = "史诗", CLASS_MASK = 256 },
      { SET_ID = 2634, NAME = "悟拳裹甲", DESCRIPTION = "随机团队", CLASS_MASK = 512 },
      { SET_ID = 2607, NAME = "悟拳裹甲", DESCRIPTION = "普通", CLASS_MASK = 512 },
      { SET_ID = 2632, NAME = "悟拳裹甲", DESCRIPTION = "英雄", CLASS_MASK = 512 },
      { SET_ID = 2633, NAME = "悟拳裹甲", DESCRIPTION = "史诗", CLASS_MASK = 512 },
      { SET_ID = 2622, NAME = "失落唤地者的戎装", DESCRIPTION = "随机团队", CLASS_MASK = 1024 },
      { SET_ID = 2603, NAME = "失落唤地者的戎装", DESCRIPTION = "普通", CLASS_MASK = 1024 },
      { SET_ID = 2620, NAME = "失落唤地者的戎装", DESCRIPTION = "英雄", CLASS_MASK = 1024 },
      { SET_ID = 2621, NAME = "失落唤地者的戎装", DESCRIPTION = "史诗", CLASS_MASK = 1024 },
      { SET_ID = 2619, NAME = "穹缚复仇者的飞行服", DESCRIPTION = "随机团队", CLASS_MASK = 2048 },
      { SET_ID = 2602, NAME = "穹缚复仇者的飞行服", DESCRIPTION = "普通", CLASS_MASK = 2048 },
      { SET_ID = 2617, NAME = "穹缚复仇者的飞行服", DESCRIPTION = "英雄", CLASS_MASK = 2048 },
      { SET_ID = 2618, NAME = "穹缚复仇者的飞行服", DESCRIPTION = "史诗", CLASS_MASK = 2048 },
      { SET_ID = 2625, NAME = "觉醒者之鳞", DESCRIPTION = "随机团队", CLASS_MASK = 4096 },
      { SET_ID = 2604, NAME = "觉醒者之鳞", DESCRIPTION = "普通", CLASS_MASK = 4096 },
      { SET_ID = 2623, NAME = "觉醒者之鳞", DESCRIPTION = "英雄", CLASS_MASK = 4096 },
      { SET_ID = 2624, NAME = "觉醒者之鳞", DESCRIPTION = "史诗", CLASS_MASK = 4096 },
    }
  },
}

TRANSMOG_SLOT_SORT = {
  1, 2, 3, 4, 7, 8, 9, 10, 11
}

-- 槽位ID与名称的对照表 (部分示例)
TRANSMOG_SLOT_NAMES = {
  [1] = "Head",
  [2] = "Shoulder",
  [3] = "Back",
  [4] = "Chest",
  [5] = "Shirt",
  [6] = "Tabard",
  [7] = "Wrist",
  [8] = "Hands",
  [9] = "Waist",
  [10] = " Legs",
  [11] = " Feet",
  [12] = " Wand",
  [13] = " OneHAxe",
  [14] = " OneHSword",
  [15] = " OneHMace",
  [16] = " Dagger",
  [17] = " Fist",
  [18] = " Shield",
  [19] = " Holdable",
  [20] = " TwoHAxe",
  [21] = " TwoHSword",
  [22] = " TwoHMace",
  [23] = " Staff",
  [24] = " Polearm",
  [25] = " Bow",
  [26] = " Gun",
  [27] = " Crossbow",
  [28] = " Warglaives",
  [29] = " Paired",
}
